# Site Settings
title: Nikita Baranov - Resume
url: 'http://baranov.tech'
baseurl: '/NikitaBaranov.github.io' #change it according to your repository name
description: "Nikita Baranov - Resume"
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Nikita Baranov
tagline: Backend Java Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
resume_pdf: Resume Nikita Baranov.pdf
summary: '
<p>Currently, I am finishing my Master’s degree program in Software Engineering at Concordia University, Montreal.</p>
<p><b>My passion is to work in a team on creation of truly smart applications.</b></p>
<p>15 years of work industry experience, as well as my latest academic endeavor, has helped me to deeply develop my
interpersonal skills, wiliness, and ability to learn fast and independently. Also, I am very adaptive and a
stress-resistant team player.</p>'

#sidebar links
email: nikita@baranov.tech
phone: 514 969 1051
# website: blog.webjeda.com #do not add http://
linkedin: NikitaBaranov
github: NikitaBaranov
# hackerrank: NikitaBaranov
# twitter: '@webjeda'
# twitter: '@webjeda'

#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# uncomment the next line, if you want the section displayed in main
# publications_in_main: True
# projects_in_main: True
# skills_in_main: True



# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
