# Site Settings
title: Nikita Baranov - Resume
url: 'http://baranov.tech'
baseurl: '/NikitaBaranov.github.io' #change it according to your repository name
description: "Nikita Baranov - Resume"
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Nikita Baranov
tagline: Backend Java Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
resume_pdf: Resume_Nikita_Baranov.pdf
resume_link: https://docs.google.com/document/d/16dPYrXONy5dp3SCb-8m5lCx6CoqF_eEFORDv6csSwZw/edit?usp=sharing
summary: '
<p><b>My passion is to work in a team on creating truly smart applications. </b></p>
<p> Software developer, critical thinker and team player with over 17 years experience of creating and
maintaining software solutions. Hands-on knowledge of different roles and phases of the software product lifecycle,
in combination with constant learning and fast skill acquisition, allows me quickly solve problems
of any kind (technical, non-technical) and deliver the best possible user experience within deadlines.</p>
<p>Recently, I started to dive into Machine-Learning and Deep Networks to enrich developed solutions
with Artificial Intelligent capabilities.</p>'

skills: '
<ul>
  <li><b>Languages/Frameworks:</b> Java 8, Spring Framework, Spring Boot, Spring Data, Python, Angular 2+, Go language</li>
  <li><b>Technologies/Standards:</b>  REST, JSON, Git, Github, jUnit, Mockito</li>
  <li><b>DB:</b> Cassandra (NoSQL), MongoDB (NoSQL), MySQL (SQL)</li>
  <li><b>Deployment:</b> Docker, Kubernetes, Google Cloud</li>
  <li><b>Big Data and Machine Learning(ML):</b> Keras, Tensorflow, Jupyter notebooks, Map-Reduce, Hadoop, Apache Spark</li>
  <li><b>Fundamentals:</b> Algorithms and Data Structures</li>
  <li><b>Soft skills:</b> agile, team player, critical thinking, problem-solving, attention to details, fast learner</li>
</ul>'

#sidebar links
email: nikita@baranov.tech
email2: NikitaBaranov@gmail.com
phone: +1-514-969-1051
# website: blog.webjeda.com #do not add http://
linkedin: NikitaBaranov
github: NikitaBaranov
# hackerrank: NikitaBaranov
# twitter: '@webjeda'

#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True
certification_in_main: True
skills_profile_in_main: True

# uncomment the next line, if you want the section displayed in main
# publications_in_main: True
# projects_in_main: True
# skills_in_main: True



# Tracker
analytics: UA-145122840-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
